name: "pre-release"

on:
  push:
    tags:
      # match semver with identifier
      - v[0-9].[0-9]+.[0-9]+-*

jobs:
  build:
    uses: ./.github/workflows/verify.yml

  tagged-release:
    needs: build
    name: Tagged Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2
      - name: build
        run: ./gradlew build
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            LICENSE.txt
            sampleproject-core/build/libs/*core.jar
