name: Verify

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [ opened, ready_for_review, synchronize ]
  push:
    branches:
      - main
      - master
      - dev*
      - feature/*
      - release/*
      - fix/*
      - renovate/*

jobs:
  build:
    environment: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18
      - name: Check licence
        run: ./gradlew licenseCheck
      - name: Build with Gradle
        run: ./gradlew --build-cache build
      - name: Test with Gradle
        run: ./gradlew test
